### GET ALL PRODUCT
GET http://localhost:9090/api/v1/product
Content-Type: application/json

### GET PRODUCT BY ID
GET http://localhost:9090/api/v1/product/1
Content-Type: application/json

### GET ALL PRODUCT TYPE
GET http://localhost:9090/api/v1/product/category
Content-Type: application/json

### CREATE A PRODUCT TYPE
POST http://localhost:9090/api/v1/product/category
Content-Type: application/json

{
  "product_category_name": "test category 2"
}

### CREATE A PRODUCT
POST http://localhost:9090/api/v1/product
Content-Type: application/json

{
  "product_code": "123asdaeqw",
  "product_name": "test product name",
  "product_image": "product1.jpg",
  "product_price": 900000000,
  "product_category_id": 3
}

### DELETE A CATEGORY
DELETE http://localhost:9090/api/v1/product/category/1

### DELETE A PRODUCT
DELETE http://localhost:9090/api/v1/product/2